### ISSUE TITLE
Temporal Dead Zone, etc.

### ISSUE THREAD

**Issue by zeveck** [nzakas/understandinges6#262]
The book says,

 "Unlike var syntax, **let** and **const** variables have no hoisting characteristics,"

but other sources say this is a wrong interpretation of what's going on (for instance, http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/). As other sources put it, the variable **is still hoisted**, it's just you can't access it. While this is similar to it not being hoisted, for memory management issues and such it feels different, and it makes me wonder about the accuracy of other statements. For example,

"Once the loop is complete, the variable is destroyed and is no longer accessible elsewhere."

is that actually true? Or is it just that the variable isn't accessible once you leave the loop and it's not really destroyed until it's scope is destroyed? The looseness of the use of the hoisting description renders other lifetime statements suspect. (Fwiw, given the above link's explanation of why hoisting is really happening, I suspect that destruction too is tied to the Lexical Environment and not the block, but am unsure.)

**Comment by nzakas** [comment]
I think we're wandering into the realm of semantic interpretation here. The text doesn't say `let` and `const` aren't hoisted, it says they are do not have hoisting characteristics. People seem to generally understand "hoist" to mean, "the variable can be used before it was declared without problem" (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting)). With that definition, saying `let` and `const` are hoisted but can't be used before they're defined is a bit confusing.

With regards to your other comments: you're right, it's inaccurate to say the variable is destroyed once the loop completes because we don't really know when it will be destroyed, we just know that it's inaccessible. Does that make a big difference to the average reader? Probably not. 

I tend to use the term "block" instead of "lexical environment" most of the time because "block" has more meaning to most readers.

Keep in mind, different authors take different approaches to explaining the same thing. Sometimes I skip over details that, while interesting, don't add much to the overall understanding of the average reader. This book is not intended to fully represent everything as described in the spec, but rather, to give readers a good overview and general understanding of the concepts.

I'll read the chapter over again and see if there are any tweaks I can make to clear up some of these points.

**Comment by getify** [comment]
I think this example illustrates that TDZ really doesn't have anything to do with hoisting:

```js
if (true) {
   let x = function() { return y; }   // <-- not a TDZ error
   let y = 2;
   x(); // 2
}
```

Whether `y` is hoisted or not, the question is *when* is `y` allowed to be accessed? In this case, `y` is accessed only after it's declared, so it's valid. That's the "temporal" in TDZ. It's a timing issue.

**Comment by zeveck** [comment]
Sorry, right, some of it is semantics, but that was just one sentence. Others are 

"Since let declarations are not hoisted to the top of the enclosing block"
"Since the variable value is declared using let instead of var, the declaration isn’t hoisted to the top of the function definition"
"That means constants are destroyed once execution flows out of the block in which they were declared, and declarations are not hoisted"
etc.

but technically they are hoisted. As far as I can tell, TDZ is the handling of the fact that they're hoisted, insofar as it is implemented as logic applied to ensure things which are technically hoisted aren't accessible. 

That said, as the end result is you can't access them until they are initialized, I totally get that it's simpler to simply say things aren't hoisted, but it caused some confusion because the description here seemed directly in conflict with descriptions elsewhere. Perhaps a sidebar explaining that while technically hoisted the distinction is unimportant and you choose to say "not hoisted" because it carries the right intuition or such? Anyways, was just reading and ran into the confusion and thought I'd mention. It's your text, after all. :)

**Comment by nzakas** [comment]
Again, I think you and I do not have the same definition of "hoist" (and obviously, not the same definition as the post you referenced). With my definition, the sentences you cite are correct and internally consistent (also the same definition as used here by @getify: https://davidwalsh.name/for-and-against-let).

So, I'm still of the mind that saying a variable is "hoisted" into the TDZ is incorrect.

That said, I'll try to clarify some of the pieces around the topic.
